services:
  nuxt-app:
    container_name: my_nuxt_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8002:8002'
    environment:
      - NODE_ENV=production
      - PORT=8002
    restart: unless-stopped
