services:
  nuxt-app:
    build: .
    image: verycoolgary/shop.web
    container_name: shop-web
    ports:
      - '8002:8002'
    environment:
      - NODE_ENV=production
      - PORT=8002
    restart: unless-stopped
