services:
  nuxt-app:
    image: verycoolgary/shop.web
    container_name: web_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8002:8002'
    environment:
      - NODE_ENV=production
      - PORT=8002
    restart: unless-stopped
